### ISSUE TITLE
API suggestion: focus on RO ArrayBuffer(s)

### ISSUE THREAD

**Issue by CrimsonCodes0** [tc39/proposal-limited-arraybuffer#8]
From the README:
> Cannot construct the read-write view from readOnlyView.buffer

To prevent this problem ^, and the potential problem mentioned on the 5th slide of the current stage 1 proposal slides, I suggest introducing a new class, `ReadOnlyArrayBuffer`, analogous to the present `SharedArrayBuffer`.

By constructing a `ReadOnlyArrayBuffer` from a read-write `ArrayBuffer`, and creating a TypedArray view on the read-only buffer, TypedArray.buffer will yield the same `ReadOnlyArrayBuffer` object.

Example:
```js
const rw_buffer = new ArrayBuffer (10);

const rw_view = new Uint8Array(rw_buffer);

// nothing changes here
for ( let i = 0; i < 10; ++i ) {
    rw_view[i] = I;
}

const ro_buffer = new ReadOnlyArrayBuffer(rw_buffer);

const ro_view = Uint8Array(ro_buffer);

assert(ro_buffer === ro_view.buffer);

// ro_view is an Uint8Array containing 0..=10
for ( let i = 0; i < 10; ++i ) {
    assert(ro_view[i] === i);
}

ro_view[0] = 1; // TypeError
```

The class would be usable in almost every place that ArrayBuffers and SharedArrayBuffers are currently usable, including DataViews, and any WebIDL functions that accept ArrayBuffer sources.

(On second thought, wouldn't there need to be a `SharedReadOnlyArrayBuffer` too?)

**Comment by Jack-Works** [comment]
Actually, I think adding more different kinds of ArrayBuffer is really not a good idea.

For example, we have SAB today and we might have [ResizableArrayBuffer and GrowableSharedArrayBuffer](https://github.com/tc39/proposal-resizablearraybuffer) in the future.

And by this route we have to do a combination on those features:

- ArrayBuffer
- ReadonlyArrayBuffer
- SharedArrayBuffer
- ReadonlySharedArrayBuffer
- ResizableArrayBuffer
- ResizableSharedArrayBuffer
- GrowableSharedArrayBuffer

(why not add functionality to the current ArrayBuffer instead of new classes? cc @syg)

**Comment by CrimsonCodes0** [comment]
Yes, once I wrote that comment at the bottom of the post, I started to doubt it too. Viewing everything as read-only, might be better, but at the same time, it would be more ergonomic if you have to create multiple views onto the same ro memory, as they wouldn't need multiple option bag arguments with `readonly: true`.

Besides that, it would end poorly , requiring separate classes for each and every intersection of ArrayBuffer subclass.

**Comment by Jack-Works** [comment]
And recently IMO ResizableArrayBuffer and GrowableSharedArrayBuffer have been rejected to stage 3 because they add new classes instead of options. I think that also applies to this one.
